language: objective-c
xcode_workspace: LPDMvvmKit.xcworkspace
xcode_scheme: LPDMvvmKit
osx_image: xcode7.1
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - FASTLANE_LANE=ci_commit
  
script: xctool -sdk iphonesimulator -workspace LPDMvvmKit.xcworkspace -scheme LPDMvvmKit build test
